export const ACCOUNT_TABLES = [
  "activity_events",
  "notification_queue",
  "usage_events",
  "deadline_reminders",
  "saved_search_alerts",
  "saved_searches",
  "requirement_suppliers",
  "workspace_suppliers",
  "supplier_notes",
  "supplier_evidence",
  "supplier_contacts",
  "supplier_brands",
  "supplier_certifications",
  "supplier_regions",
  "supplier_capabilities",
  "suppliers",
  "submission_checklist_items",
  "compliance_items",
  "tender_requirements",
  "tender_documents",
  "bid_workspaces",
  "tender_analyses",
  "saved_opportunities",
  "company_certifications",
  "company_regions",
  "company_capabilities",
  "company_business_models",
  "companies",
  "subscription_accounts",
] as const;
export function storageCleanupPrefix(userId: string) {
  return `${userId}/`;
}
