/* eslint-disable react-hooks/purity, react-hooks/exhaustive-deps -- deadline is snapshotted per workspace session */
"use client";
import { useMemo, useState } from "react";
import type { Opportunity } from "@/lib/opportunities/types";
import { calculateBidReadiness } from "@/lib/bid-workspace/readiness";
import { nextBidActions, simpleRequirementStatus } from "@/lib/bid-workspace/presentation";
import type { ComplianceStatus, RequirementLike } from "@/lib/bid-workspace/types";
type Row = Record<string, unknown>;
type WorkspaceData = { workspace: Row; documents: Row[]; requirements: Row[]; compliance: Row[]; checklist: Row[] };
const TABS = ["Overview", "Documents", "Requirements", "Readiness"] as const;
const pretty = (value: unknown) => String(value ?? "").split("_").map((x) => x[0]?.toUpperCase() + x.slice(1)).join(" ");

export function BidWorkspace({ opportunity, initial, matchScore }: { opportunity: Opportunity; initial: WorkspaceData | null; matchScore: number | null }) {
  const [data, setData] = useState(initial), [tab, setTab] = useState<(typeof TABS)[number]>("Overview"), [busy, setBusy] = useState(false), [message, setMessage] = useState("");
  const requirements = data?.requirements ?? [], documents = data?.documents ?? [], compliance = data?.compliance ?? [], checklist = data?.checklist ?? [];
  const daysRemaining = opportunity.deadline ? Math.ceil((new Date(opportunity.deadline).getTime() - Date.now()) / 86400000) : null;
  const readiness = useMemo(() => calculateBidReadiness({ items: requirements.map((r) => { const c = compliance.find((x) => x.requirement_id === r.id); return { requirement: { title: String(r.title), description: String(r.description), requirementType: String(r.requirement_type), mandatoryStatus: String(r.mandatory_status), confidence: String(r.confidence) } as RequirementLike, status: String(c?.status ?? "needs_review") as ComplianceStatus, evidenceAvailable: Boolean(c?.evidence_document_id) }; }), submissionCompleted: checklist.filter((x) => x.completed).length, submissionTotal: checklist.length, daysRemaining }), [requirements, compliance, checklist, daysRemaining]);
  const rows = requirements.map((r) => ({ r, c: compliance.find((x) => x.requirement_id === r.id) }));
  const missing = rows.filter(({ c }) => ["missing", "needs_evidence"].includes(String(c?.status ?? "needs_review")));
  const actions = nextBidActions({ documents: documents.length, requirements: requirements.length, missing: missing.map(({ r }) => String(r.title)), checklistOpen: checklist.filter((x) => !x.completed).map((x) => String(x.label)) });
  const refresh = async () => { const r = await fetch(`/api/bid-workspaces/${opportunity.id}`), j = await r.json(); if (r.ok) setData(j.bidWorkspace); };
  const start = async () => { setBusy(true); setMessage(""); try { const r = await fetch(`/api/bid-workspaces/${opportunity.id}`, { method: "POST" }), j = await r.json(); if (!r.ok) throw new Error(j.error); setData(j.bidWorkspace); setMessage("Bid review started."); } catch (e) { setMessage(e instanceof Error ? e.message : "Bid review could not be started."); } finally { setBusy(false); } };
  const upload = async (e: React.FormEvent<HTMLFormElement>) => { e.preventDefault(); const form = e.currentTarget, file = new FormData(form).get("file"); if (!(file instanceof File) || !file.size) return; setBusy(true); setMessage("Uploading document…"); try { const body = new FormData(); body.set("file", file); const r = await fetch(`/api/bid-workspaces/${opportunity.id}/documents`, { method: "POST", body }), j = await r.json(); if (!r.ok) throw new Error(j.error); await refresh(); form.reset(); setMessage(j.warning ?? "Document ready."); } catch (e) { setMessage(e instanceof Error ? e.message : "Upload failed. Please try again."); } finally { setBusy(false); } };
  const updateRequirement = async (id: string, body: object) => { await fetch(`/api/bid-workspaces/${opportunity.id}/compliance/${id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify(body) }); await refresh(); };
  const updateChecklist = async (id: string, completed: boolean) => { await fetch(`/api/bid-workspaces/${opportunity.id}/checklist/${id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ completed }) }); await refresh(); };
  const decision = async (value: string) => { await fetch(`/api/bid-workspaces/${opportunity.id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ decision: value }) }); await refresh(); };
  const view = async (id: unknown) => { const r = await fetch(`/api/bid-workspaces/${opportunity.id}/documents/${id}`), j = await r.json(); if (r.ok) window.open(j.url, "_blank", "noopener,noreferrer"); else setMessage(j.error); };
  const remove = async (id: unknown) => { const r = await fetch(`/api/bid-workspaces/${opportunity.id}/documents/${id}`, { method: "DELETE" }), j = await r.json(); if (!r.ok) return setMessage(j.error); await refresh(); setMessage("Document removed."); };
  return <section className="bid-workspace" id="bid-workspace">
    <header className="workspace-heading"><div><span className="section-label">PRIVATE BID REVIEW</span><h2>Bid workspace</h2><p>Understand the tender, identify what is missing, and decide what to do next.</p></div>{data ? <div className="readiness-orb"><strong>{readiness.score}%</strong><span>ready</span></div> : null}</header>
    {!data ? <div className="workspace-onboarding"><span className="section-label">START YOUR BID REVIEW</span><ol><li><b>Analyze the opportunity</b><span>Understand the notice and likely requirements.</span></li><li><b>Upload tender documents</b><span>IPO will identify requirements and missing proof.</span></li><li><b>Review your readiness</b><span>See what is ready, missing, or needs review.</span></li></ol><div><a className="black-button" href="#ai-analysis">Analyze tender with AI</a><button onClick={start} disabled={busy}>{busy ? "Starting…" : "Start and upload documents"}</button></div></div> : <>
      <nav className="workspace-tabs" aria-label="Bid workspace sections">{TABS.map((x) => <button key={x} className={tab === x ? "active" : ""} onClick={() => setTab(x)}>{x}</button>)}</nav>
      {tab === "Overview" ? <div className="workspace-overview"><div className="decision-metrics five"><Metric label="MATCH" value={matchScore === null ? "—" : `${matchScore}%`} /><Metric label="BID READINESS" value={`${readiness.score}%`} /><Metric label="DEADLINE" value={daysRemaining === null ? "Unknown" : daysRemaining < 0 ? "Closed" : `${daysRemaining} days`} /><Metric label="MISSING" value={`${missing.length} items`} /><Metric label="DECISION" value={pretty(data.workspace.decision || "undecided")} /></div><section className="next-actions"><span className="section-label">NEXT BEST ACTIONS</span>{actions.length ? <ol>{actions.map((x) => <li key={x}>{x}</li>)}</ol> : <p>Your core requirements are addressed. Verify the official notice and complete submission checks.</p>}</section><div className="decision-control"><span>Bid decision</span>{[["pursue","Pursue"],["review","Review"],["do_not_bid","Do not pursue"]].map(([v,l]) => <button key={v} className={data.workspace.decision === v ? "active" : ""} onClick={() => decision(v)}>{l}</button>)}</div></div> : null}
      {tab === "Documents" ? <div className="workspace-panel"><PanelIntro title="Tender files" text="Upload and review the files for this tender." /><form className="document-upload" onSubmit={upload}><span className="section-label">UPLOAD TENDER DOCUMENTS</span><input aria-label="Tender document" name="file" type="file" accept=".pdf,.docx,.txt,application/pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document,text/plain" required /><button className="black-button" disabled={busy}>{busy ? "Processing…" : "Choose and upload file"}</button><small>Drag & drop or choose files · PDF, DOCX or TXT · up to 20 MB</small></form><div className="document-list">{documents.length ? documents.map((d) => <article key={String(d.id)}><div><b>{String(d.filename)}</b><small>{pretty(d.processing_status)} · {new Date(String(d.created_at)).toLocaleDateString()}</small>{d.processing_status === "ready" ? <small>Requirements found: {requirements.filter((r) => r.source_document_id === d.id).length}</small> : null}</div><div><button onClick={() => view(d.id)}>View</button><button onClick={() => setTab("Requirements")} disabled={d.processing_status !== "ready"}>Analyze</button><button onClick={() => remove(d.id)}>Remove</button></div></article>) : <Empty text="No tender files uploaded yet." />}</div></div> : null}
      {tab === "Requirements" ? <div className="workspace-panel"><PanelIntro title="Requirements" text="Review what the tender asks for and attach proof where needed." /><div className="requirement-cards">{rows.length ? rows.map(({r,c}) => { const status = String(c?.status ?? "needs_review") as ComplianceStatus; return <article key={String(r.id)}><header><div><b>{String(r.title)}</b><span className={`simple-status ${status}`}>{simpleRequirementStatus(status)}</span></div><small>{["mandatory","appears_mandatory"].includes(String(r.mandatory_status)) ? "Required" : "May be required"}</small></header><p>{String(r.description)}</p><dl><div><dt>Source</dt><dd>{String(r.source_reference ?? "Tender document")}</dd></div><div><dt>Status</dt><dd><select aria-label={`Status for ${r.title}`} value={status} onChange={(e) => c && updateRequirement(String(c.id), { status: e.target.value })}>{[["meets","Ready"],["needs_evidence","Need evidence"],["missing","Missing"],["needs_review","Review"]].map(([v,l]) => <option key={v} value={v}>{l}</option>)}</select></dd></div><div><dt>Proof / document</dt><dd><select aria-label={`Proof for ${r.title}`} value={String(c?.evidence_document_id ?? "")} onChange={(e) => c && updateRequirement(String(c.id), { evidence_document_id: e.target.value || null })}><option value="">Add evidence</option>{documents.map((d) => <option key={String(d.id)} value={String(d.id)}>{String(d.filename)}</option>)}</select></dd></div></dl></article>; }) : <Empty text="Upload a tender document to identify detailed requirements." />}</div></div> : null}
      {tab === "Readiness" ? <div className="workspace-panel readiness-panel"><div className="readiness-summary"><span className="section-label">BID READINESS</span><strong>{readiness.score}%</strong><p>{readiness.addressedCount} of {readiness.totalRequirements} requirements addressed · {readiness.blockers.length} blockers</p></div><ReadinessGroup title="READY" symbol="✓" rows={rows.filter(({c}) => simpleRequirementStatus(String(c?.status ?? "needs_review") as ComplianceStatus) === "Ready").map(({r}) => String(r.title))} /><ReadinessGroup title="NEEDS ATTENTION" symbol="!" rows={rows.filter(({c}) => ["Need evidence","Review"].includes(simpleRequirementStatus(String(c?.status ?? "needs_review") as ComplianceStatus))).map(({r}) => String(r.title))} /><ReadinessGroup title="BLOCKERS" symbol="×" rows={readiness.blockers.map((x) => x.requirement.title)} /><section className="readiness-checklist"><h3>Next steps</h3>{checklist.map((x) => <label key={String(x.id)}><input type="checkbox" checked={Boolean(x.completed)} onChange={(e) => updateChecklist(String(x.id), e.target.checked)} /><span>{String(x.label)}</span></label>)}</section></div> : null}
    </>}
    {message ? <div className="workspace-message" role="status">{message}</div> : null}
  </section>;
}
function Metric({ label, value }: { label: string; value: string }) { return <div><span>{label}</span><strong>{value}</strong></div>; }
function Empty({ text }: { text: string }) { return <div className="state-card"><p>{text}</p></div>; }
function PanelIntro({ title, text }: { title: string; text: string }) { return <header className="panel-intro"><h3>{title}</h3><p>{text}</p></header>; }
function ReadinessGroup({ title, symbol, rows }: { title: string; symbol: string; rows: string[] }) { return <section className={`readiness-group ${title === "BLOCKERS" ? "blockers" : ""}`}><h3>{title}</h3>{rows.length ? rows.map((x) => <p key={x}><span>{symbol}</span>{x}</p>) : <small>None identified.</small>}</section>; }
export default BidWorkspace;
