create extension if not exists pgcrypto;
create or replace function public.set_updated_at() returns trigger language plpgsql set search_path='' as $$ begin new.updated_at=now(); return new; end; $$;

create table public.profiles(id uuid primary key references auth.users(id) on delete cascade,email text not null,display_name text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.companies(id uuid primary key default gen_random_uuid(),user_id uuid not null unique references auth.users(id) on delete cascade,name text not null default '',country text not null default '',website text not null default '',min_contract_value numeric check(min_contract_value>=0),max_contract_value numeric check(max_contract_value>=0),preferred_currency text check(preferred_currency is null or preferred_currency~'^[A-Z]{3}$'),government_experience text not null default 'None',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check(max_contract_value is null or min_contract_value is null or max_contract_value>=min_contract_value));
create table public.company_business_models(company_id uuid not null references public.companies(id) on delete cascade,business_model text not null,primary key(company_id,business_model));
create table public.company_capabilities(company_id uuid not null references public.companies(id) on delete cascade,capability text not null,primary key(company_id,capability));
create table public.company_regions(company_id uuid not null references public.companies(id) on delete cascade,region text not null,primary key(company_id,region));
create table public.company_certifications(id uuid primary key default gen_random_uuid(),company_id uuid not null references public.companies(id) on delete cascade,certification_name text not null,unique(company_id,certification_name));
create table public.saved_opportunities(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,source text not null,source_opportunity_id text not null,opportunity_title text not null,buyer_name text,source_url text,saved_at timestamptz not null default now(),unique(user_id,source,source_opportunity_id));
create table public.ai_tender_analyses(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,source text not null,source_opportunity_id text not null,source_updated_at timestamptz,model text not null,analysis_json jsonb not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create unique index ai_analysis_fresh_idx on public.ai_tender_analyses(user_id,source,source_opportunity_id,coalesce(source_updated_at,'epoch'::timestamptz));
create table public.user_preferences(user_id uuid primary key references auth.users(id) on delete cascade,preferred_currency text check(preferred_currency is null or preferred_currency~'^[A-Z]{3}$'),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create index companies_user_idx on public.companies(user_id);create index saved_user_idx on public.saved_opportunities(user_id);create index analysis_user_idx on public.ai_tender_analyses(user_id);create index business_company_idx on public.company_business_models(company_id);create index capabilities_company_idx on public.company_capabilities(company_id);create index regions_company_idx on public.company_regions(company_id);create index certifications_company_idx on public.company_certifications(company_id);

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path='' as $$ begin insert into public.profiles(id,email,display_name) values(new.id,coalesce(new.email,''),new.raw_user_meta_data->>'display_name'); return new; end; $$;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();
create trigger profiles_updated before update on public.profiles for each row execute function public.set_updated_at();create trigger companies_updated before update on public.companies for each row execute function public.set_updated_at();create trigger analyses_updated before update on public.ai_tender_analyses for each row execute function public.set_updated_at();create trigger preferences_updated before update on public.user_preferences for each row execute function public.set_updated_at();

alter table public.profiles enable row level security;alter table public.companies enable row level security;alter table public.company_business_models enable row level security;alter table public.company_capabilities enable row level security;alter table public.company_regions enable row level security;alter table public.company_certifications enable row level security;alter table public.saved_opportunities enable row level security;alter table public.ai_tender_analyses enable row level security;alter table public.user_preferences enable row level security;
revoke all on all tables in schema public from anon;grant select,insert,update,delete on public.profiles,public.companies,public.company_business_models,public.company_capabilities,public.company_regions,public.company_certifications,public.saved_opportunities,public.ai_tender_analyses,public.user_preferences to authenticated;

create policy profiles_select on public.profiles for select to authenticated using((select auth.uid())=id);create policy profiles_update on public.profiles for update to authenticated using((select auth.uid())=id) with check((select auth.uid())=id);
create policy companies_select on public.companies for select to authenticated using((select auth.uid())=user_id);create policy companies_insert on public.companies for insert to authenticated with check((select auth.uid())=user_id);create policy companies_update on public.companies for update to authenticated using((select auth.uid())=user_id) with check((select auth.uid())=user_id);create policy companies_delete on public.companies for delete to authenticated using((select auth.uid())=user_id);
create or replace function public.owns_company(target uuid) returns boolean language sql security definer stable set search_path='' as $$select exists(select 1 from public.companies where id=target and user_id=(select auth.uid()))$$;revoke execute on function public.owns_company(uuid) from public;grant execute on function public.owns_company(uuid) to authenticated;
create policy business_all on public.company_business_models for all to authenticated using(public.owns_company(company_id)) with check(public.owns_company(company_id));create policy capabilities_all on public.company_capabilities for all to authenticated using(public.owns_company(company_id)) with check(public.owns_company(company_id));create policy regions_all on public.company_regions for all to authenticated using(public.owns_company(company_id)) with check(public.owns_company(company_id));create policy certifications_all on public.company_certifications for all to authenticated using(public.owns_company(company_id)) with check(public.owns_company(company_id));
create policy saved_select on public.saved_opportunities for select to authenticated using((select auth.uid())=user_id);create policy saved_insert on public.saved_opportunities for insert to authenticated with check((select auth.uid())=user_id);create policy saved_update on public.saved_opportunities for update to authenticated using((select auth.uid())=user_id) with check((select auth.uid())=user_id);create policy saved_delete on public.saved_opportunities for delete to authenticated using((select auth.uid())=user_id);
create policy analyses_select on public.ai_tender_analyses for select to authenticated using((select auth.uid())=user_id);create policy analyses_insert on public.ai_tender_analyses for insert to authenticated with check((select auth.uid())=user_id);create policy analyses_update on public.ai_tender_analyses for update to authenticated using((select auth.uid())=user_id) with check((select auth.uid())=user_id);create policy analyses_delete on public.ai_tender_analyses for delete to authenticated using((select auth.uid())=user_id);
create policy preferences_select on public.user_preferences for select to authenticated using((select auth.uid())=user_id);create policy preferences_insert on public.user_preferences for insert to authenticated with check((select auth.uid())=user_id);create policy preferences_update on public.user_preferences for update to authenticated using((select auth.uid())=user_id) with check((select auth.uid())=user_id);create policy preferences_delete on public.user_preferences for delete to authenticated using((select auth.uid())=user_id);
