create table public.suppliers(
  id uuid primary key default gen_random_uuid(), owner_user_id uuid references auth.users(id) on delete cascade,
  name text not null check(char_length(name) between 1 and 300), website text,
  country text not null default '', description text not null default '',
  supplier_type text not null check(supplier_type in ('manufacturer','distributor','reseller','systems_integrator','service_provider','logistics_provider','subcontractor')),
  verification_status text not null default 'unverified' check(verification_status in ('unverified','user_verified','source_verified')),
  estimated_capacity_notes text, lead_time_notes text, minimum_order_notes text, general_notes text,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table public.supplier_capabilities(supplier_id uuid not null references public.suppliers(id) on delete cascade,capability text not null,primary key(supplier_id,capability));
create table public.supplier_regions(supplier_id uuid not null references public.suppliers(id) on delete cascade,region text not null,primary key(supplier_id,region));
create table public.supplier_certifications(id uuid primary key default gen_random_uuid(),supplier_id uuid not null references public.suppliers(id) on delete cascade,certification_name text not null,unique(supplier_id,certification_name));
create table public.supplier_brands(id uuid primary key default gen_random_uuid(),supplier_id uuid not null references public.suppliers(id) on delete cascade,brand_name text not null,unique(supplier_id,brand_name));
create table public.supplier_contacts(id uuid primary key default gen_random_uuid(),supplier_id uuid not null references public.suppliers(id) on delete cascade,contact_name text,email text,phone text,role text,source text);
create table public.supplier_notes(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,supplier_id uuid not null references public.suppliers(id) on delete cascade,note text not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.workspace_suppliers(
 id uuid primary key default gen_random_uuid(),bid_workspace_id uuid not null references public.bid_workspaces(id) on delete cascade,supplier_id uuid not null references public.suppliers(id) on delete restrict,
 role text not null default 'potential_supplier',status text not null default 'potential' check(status in ('potential','reviewing','selected','rejected')),
 quote_status text not null default 'not_requested' check(quote_status in ('not_requested','requested','received','declined','expired')),
 quoted_amount numeric check(quoted_amount is null or quoted_amount>=0),quoted_currency text check(quoted_currency is null or quoted_currency~'^[A-Z]{3}$'),
 lead_time_days integer check(lead_time_days is null or lead_time_days between 0 and 3650),quote_valid_until date,notes text,
 logistics_cost numeric check(logistics_cost is null or logistics_cost>=0),other_cost numeric check(other_cost is null or other_cost>=0),
 created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(bid_workspace_id,supplier_id)
);
create table public.requirement_suppliers(
 id uuid primary key default gen_random_uuid(),requirement_id uuid not null references public.tender_requirements(id) on delete cascade,supplier_id uuid not null references public.suppliers(id) on delete restrict,
 workspace_supplier_id uuid references public.workspace_suppliers(id) on delete cascade,suitability_status text not null default 'potential' check(suitability_status in ('potential','reviewing','suitable','unsuitable')),
 notes text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(requirement_id,supplier_id)
);
create table public.supplier_evidence(id uuid primary key default gen_random_uuid(),supplier_id uuid not null references public.suppliers(id) on delete cascade,user_id uuid not null references auth.users(id) on delete cascade,evidence_type text not null,source_url text,description text,created_at timestamptz not null default now());
create index suppliers_owner_idx on public.suppliers(owner_user_id);create index suppliers_country_type_idx on public.suppliers(country,supplier_type);create index supplier_capability_idx on public.supplier_capabilities(capability);create index workspace_suppliers_workspace_idx on public.workspace_suppliers(bid_workspace_id);create index requirement_suppliers_requirement_idx on public.requirement_suppliers(requirement_id);
create unique index private_supplier_domain_idx on public.suppliers(owner_user_id,lower(regexp_replace(website,'^https?://(www\.)?',''))) where owner_user_id is not null and website is not null and website<>'';
create trigger suppliers_updated before update on public.suppliers for each row execute function public.set_updated_at();create trigger supplier_notes_updated before update on public.supplier_notes for each row execute function public.set_updated_at();create trigger workspace_suppliers_updated before update on public.workspace_suppliers for each row execute function public.set_updated_at();create trigger requirement_suppliers_updated before update on public.requirement_suppliers for each row execute function public.set_updated_at();
alter table public.suppliers enable row level security;alter table public.supplier_capabilities enable row level security;alter table public.supplier_regions enable row level security;alter table public.supplier_certifications enable row level security;alter table public.supplier_brands enable row level security;alter table public.supplier_contacts enable row level security;alter table public.supplier_notes enable row level security;alter table public.workspace_suppliers enable row level security;alter table public.requirement_suppliers enable row level security;alter table public.supplier_evidence enable row level security;
grant select,insert,update,delete on public.suppliers,public.supplier_capabilities,public.supplier_regions,public.supplier_certifications,public.supplier_brands,public.supplier_contacts,public.supplier_notes,public.workspace_suppliers,public.requirement_suppliers,public.supplier_evidence to authenticated;
create or replace function public.can_read_supplier(target uuid) returns boolean language sql security definer stable set search_path='' as $$select exists(select 1 from public.suppliers s where s.id=target and (s.owner_user_id is null or s.owner_user_id=(select auth.uid())))$$;revoke execute on function public.can_read_supplier(uuid) from public;grant execute on function public.can_read_supplier(uuid) to authenticated;
create or replace function public.owns_supplier(target uuid) returns boolean language sql security definer stable set search_path='' as $$select exists(select 1 from public.suppliers s where s.id=target and s.owner_user_id=(select auth.uid()))$$;revoke execute on function public.owns_supplier(uuid) from public;grant execute on function public.owns_supplier(uuid) to authenticated;
create or replace function public.owns_bid_workspace(target uuid) returns boolean language sql security definer stable set search_path='' as $$select exists(select 1 from public.bid_workspaces w where w.id=target and w.user_id=(select auth.uid()))$$;revoke execute on function public.owns_bid_workspace(uuid) from public;grant execute on function public.owns_bid_workspace(uuid) to authenticated;
create policy suppliers_read on public.suppliers for select to authenticated using(owner_user_id is null or owner_user_id=(select auth.uid()));create policy suppliers_insert on public.suppliers for insert to authenticated with check(owner_user_id=(select auth.uid()) and verification_status in ('unverified','user_verified'));create policy suppliers_update on public.suppliers for update to authenticated using(owner_user_id=(select auth.uid())) with check(owner_user_id=(select auth.uid()) and verification_status in ('unverified','user_verified'));create policy suppliers_delete on public.suppliers for delete to authenticated using(owner_user_id=(select auth.uid()));
create policy supplier_capabilities_read on public.supplier_capabilities for select to authenticated using(public.can_read_supplier(supplier_id));create policy supplier_capabilities_write on public.supplier_capabilities for all to authenticated using(public.owns_supplier(supplier_id)) with check(public.owns_supplier(supplier_id));create policy supplier_regions_read on public.supplier_regions for select to authenticated using(public.can_read_supplier(supplier_id));create policy supplier_regions_write on public.supplier_regions for all to authenticated using(public.owns_supplier(supplier_id)) with check(public.owns_supplier(supplier_id));create policy supplier_certifications_read on public.supplier_certifications for select to authenticated using(public.can_read_supplier(supplier_id));create policy supplier_certifications_write on public.supplier_certifications for all to authenticated using(public.owns_supplier(supplier_id)) with check(public.owns_supplier(supplier_id));create policy supplier_brands_read on public.supplier_brands for select to authenticated using(public.can_read_supplier(supplier_id));create policy supplier_brands_write on public.supplier_brands for all to authenticated using(public.owns_supplier(supplier_id)) with check(public.owns_supplier(supplier_id));create policy supplier_contacts_owner on public.supplier_contacts for all to authenticated using(public.owns_supplier(supplier_id)) with check(public.owns_supplier(supplier_id));
create policy supplier_notes_owner on public.supplier_notes for all to authenticated using(user_id=(select auth.uid()) and public.can_read_supplier(supplier_id)) with check(user_id=(select auth.uid()) and public.can_read_supplier(supplier_id));create policy supplier_evidence_owner on public.supplier_evidence for all to authenticated using(user_id=(select auth.uid()) and public.can_read_supplier(supplier_id)) with check(user_id=(select auth.uid()) and public.can_read_supplier(supplier_id));
create policy workspace_suppliers_owner on public.workspace_suppliers for all to authenticated using(public.owns_bid_workspace(bid_workspace_id) and public.can_read_supplier(supplier_id)) with check(public.owns_bid_workspace(bid_workspace_id) and public.can_read_supplier(supplier_id));
create policy requirement_suppliers_owner on public.requirement_suppliers for all to authenticated using(exists(select 1 from public.tender_requirements r where r.id=requirement_id and r.user_id=(select auth.uid())) and public.can_read_supplier(supplier_id)) with check(exists(select 1 from public.tender_requirements r where r.id=requirement_id and r.user_id=(select auth.uid())) and public.can_read_supplier(supplier_id));
