import type { CompanyProfile, Opportunity } from "./types";
export const MOCK_OPPORTUNITIES: Opportunity[] = [
  {
    id: "rugged-computing",
    reference: "EU-2026-09417",
    title: "Supply of Ruggedised Computing Equipment",
    buyer: {
      id: "eda",
      name: "European Defence Organisation",
      type: "Intergovernmental body",
      country: "Belgium",
    },
    country: "Belgium",
    category: "IT & Communications",
    value: 2800000,
    currency: "EUR",
    publishedAt: "12 Aug 2026",
    deadline: "18 Sep 2026",
    eligibility: "Eligible region",
    summary:
      "A four-year framework for rugged laptops, mobile workstations and supporting services across multiple operational locations.",
    match: {
      score: 94,
      derivedByAi: true,
      reasons: [
        "Company location is eligible",
        "Relevant IT capability",
        "Contract value within company range",
        "Reseller/distributor model permitted",
      ],
      issues: [
        "ISO 27001 may be required",
        "Minimum liability insurance should be reviewed",
      ],
    },
    requirements: [
      {
        id: "r1",
        title: "Information security",
        detail:
          "Evidence of an ISO 27001-aligned information security management system.",
        mandatory: true,
      },
      {
        id: "r2",
        title: "Relevant delivery history",
        detail:
          "Two comparable supply contracts completed in the last three years.",
        mandatory: true,
      },
      {
        id: "r3",
        title: "Product warranty",
        detail: "Minimum three-year manufacturer-backed warranty.",
        mandatory: true,
      },
    ],
    documents: [
      { id: "d1", name: "Contract notice", type: "PDF", size: "1.2 MB" },
      {
        id: "d2",
        name: "Technical specification",
        type: "PDF",
        size: "4.8 MB",
      },
      { id: "d3", name: "Pricing schedule", type: "XLSX", size: "240 KB" },
    ],
    saved: true,
  },
  {
    id: "cyber-monitoring",
    reference: "UK-2026-3118",
    title: "Managed Cybersecurity Monitoring Service",
    buyer: {
      id: "uk",
      name: "Cabinet Digital Services",
      type: "Central government",
      country: "United Kingdom",
    },
    country: "United Kingdom",
    category: "Cybersecurity",
    value: 1450000,
    currency: "GBP",
    publishedAt: "18 Aug 2026",
    deadline: "11 Sep 2026",
    eligibility: "Review required",
    summary:
      "Managed security monitoring and incident triage for a central government department.",
    match: {
      score: 87,
      derivedByAi: true,
      reasons: [
        "Cybersecurity capability aligns",
        "Service provider model accepted",
        "Value is within target range",
      ],
      issues: ["UK data residency requirement needs confirmation"],
    },
    requirements: [],
    documents: [],
    saved: true,
  },
  {
    id: "network-modernisation",
    reference: "DK-2026-8810",
    title: "Regional Network Infrastructure Modernisation",
    buyer: {
      id: "dk",
      name: "Capital Region Procurement",
      type: "Regional government",
      country: "Denmark",
    },
    country: "Denmark",
    category: "Networking",
    value: 4200000,
    currency: "EUR",
    publishedAt: "20 Aug 2026",
    deadline: "27 Sep 2026",
    eligibility: "Eligible region",
    summary:
      "Replacement of campus switching and network management infrastructure.",
    match: {
      score: 81,
      derivedByAi: true,
      reasons: [
        "Networking capability aligns",
        "Regional eligibility appears met",
      ],
      issues: ["Local-language support may be required"],
    },
    requirements: [],
    documents: [],
  },
  {
    id: "fleet-parts",
    reference: "NL-2026-1192",
    title: "Framework for Municipal Fleet Parts",
    buyer: {
      id: "ams",
      name: "Amsterdam Municipal Services",
      type: "Local government",
      country: "Netherlands",
    },
    country: "Netherlands",
    category: "Vehicles",
    value: 980000,
    currency: "EUR",
    publishedAt: "22 Aug 2026",
    deadline: "6 Oct 2026",
    eligibility: "Review required",
    summary: "Multi-supplier framework for routine commercial vehicle parts.",
    match: {
      score: 68,
      derivedByAi: true,
      reasons: ["Contract range aligns"],
      issues: ["Vehicle capability is not a primary company category"],
    },
    requirements: [],
    documents: [],
  },
];
export const MOCK_COMPANY: CompanyProfile = {
  name: "Northstar Systems Ltd",
  country: "Ireland",
  website: "northstarsystems.example",
  capabilities: [
    "IT",
    "Cybersecurity",
    "Software",
    "Electronics",
    "Communications",
  ],
  businessModels: [
    "Distributor",
    "Reseller",
    "Systems Integrator",
    "Service Provider",
  ],
  minContractValue: 250000,
  maxContractValue: 6000000,
  regions: ["European Union", "United Kingdom", "NATO member states"],
  certifications: ["ISO 9001", "Cyber Essentials Plus"],
  governmentExperience:
    "5 completed public-sector contracts in the past three years.",
};
